import {hashPassword} from '../core/password.js';

export async function generateHash(password: string) {
  const {hash, salt} = await hashPassword(password);
  console.log('// Generated by: `root-password-protect generate-hash "..."`.');
  console.log('password: {');
  console.log(`  hash: '${hash}',`);
  console.log(`  salt: '${salt}',`);
  console.log('}');
}
