packages:
  - "docs"
  - "apps/*"
  - "examples/*"
  - "packages/*"
allowBuilds:
  '@firebase/util': true
  '@parcel/watcher': false
  esbuild: true
  protobufjs: true
  re2: true
  unrs-resolver: true
autoInstallPeers: false
minimumReleaseAgeExclude:
  - '@typescript/typescript-aix-ppc64@7.0.2'
  - '@typescript/typescript-darwin-arm64@7.0.2'
  - '@typescript/typescript-darwin-x64@7.0.2'
  - '@typescript/typescript-freebsd-arm64@7.0.2'
  - '@typescript/typescript-freebsd-x64@7.0.2'
  - '@typescript/typescript-linux-arm64@7.0.2'
  - '@typescript/typescript-linux-arm@7.0.2'
  - '@typescript/typescript-linux-loong64@7.0.2'
  - '@typescript/typescript-linux-mips64el@7.0.2'
  - '@typescript/typescript-linux-ppc64@7.0.2'
  - '@typescript/typescript-linux-riscv64@7.0.2'
  - '@typescript/typescript-linux-s390x@7.0.2'
  - '@typescript/typescript-linux-x64@7.0.2'
  - '@typescript/typescript-netbsd-arm64@7.0.2'
  - '@typescript/typescript-netbsd-x64@7.0.2'
  - '@typescript/typescript-openbsd-arm64@7.0.2'
  - '@typescript/typescript-openbsd-x64@7.0.2'
  - '@typescript/typescript-sunos-x64@7.0.2'
  - '@typescript/typescript-win32-arm64@7.0.2'
  - '@typescript/typescript-win32-x64@7.0.2'
  - typescript@7.0.2
  - '@ai-sdk/anthropic@4.0.62'
  - '@ai-sdk/gateway@4.0.91'
  - '@ai-sdk/google-vertex@5.0.92'
  - '@ai-sdk/google@4.0.79'
  - '@ai-sdk/mcp@2.0.57'
  - '@ai-sdk/openai-compatible@3.0.55'
  - '@ai-sdk/openai@4.0.74'
  - '@ai-sdk/provider-utils@5.0.47'
  - '@ai-sdk/react@4.0.116'
  - ai@7.0.113
verifyDepsBeforeRun: warn
