import path from 'node:path';
import {URL} from 'node:url';
import {defineConfig} from '@blinkk/root';
import {cmsPlugin} from '@blinkk/root-cms/plugin';
import {passwordProtectPlugin} from '@blinkk/root-password-protect/plugin';

const rootDir = new URL('.', import.meta.url).pathname;

export default defineConfig({
  domain: 'https://rootjs.dev',
  i18n: {
    locales: ['en', 'es', 'pt_br', 'de', 'fr', 'it', 'ja', 'ko', 'zh'],
    groups: {
      americas: {
        label: 'Americas',
        locales: ['en', 'es', 'pt_br'],
      },
      emea: {
        label: 'EMEA',
        locales: ['de', 'fr', 'it'],
      },
      japac: {
        label: 'JAPAC',
        locales: ['ja', 'ko', 'zh'],
      },
    },
  },
  vite: {
    resolve: {
      alias: {
        '@': path.resolve(rootDir),
      },
    },
    css: {
      preprocessorOptions: {
        scss: {
          includePaths: [path.resolve(rootDir, './styles')],
        },
      },
    },
  },
  server: {
    trailingSlash: false,
    sessionCookieSecret: 'session-secret-change-me!',
    redirects: [
      {source: '/news', destination: '/blog'},
      {source: '/news/[slug]', destination: '/blog/[slug]'},
      {source: '/restricted/[...path]', destination: '/unauthorized'},
    ],
    headers: [
      {
        source: '/test-json.txt',
        headers: [{key: 'content-type', value: 'application/json'}],
      },
    ],
  },
  plugins: [
    cmsPlugin({
      id: 'examples-blog',
      name: 'Examples: Blog',
      firebaseConfig: {
        apiKey: 'AIzaSyDIoi6zECKeyJoCduYEmV5j9PIF-wbpaPo',
        authDomain: 'rootjs-dev.firebaseapp.com',
        projectId: 'rootjs-dev',
        storageBucket: 'rootjs-dev.appspot.com',
        messagingSenderId: '636169634531',
        appId: '1:636169634531:web:7b8fe398f10e5d9c4e7bd6',
        measurementId: 'G-5JTQHSPWBB',
      },
      storageConfig: {
        apiKey: 'AIzaSyDIoi6zECKeyJoCduYEmV5j9PIF-wbpaPo',
        authDomain: 'rootjs-dev.firebaseapp.com',
        projectId: 'rootjs-dev',
        storageBucket: 'rootjs-dev.appspot.com',
      },
      gapi: {
        apiKey: process.env.GAPI_API_KEY,
        clientId: process.env.GAPI_CLIENT_ID,
      },
      gci: true,
    }),
    passwordProtectPlugin({
      protectedRoutes: [
        {
          source: '/protected/**',
          // Generated by: `root-password-protect generate-hash "..."`.
          password: {
            hash: '65c933288e2d8c81476add7cc77285c7a3b095a040a2392e0cc79512e8f372124e6c84cea745d70e93bcf147dcc565d464fb3f15d0c299ec435027c1be26d809',
            salt: '63e8d444544a61642904b1440cdea79e',
          },
        },
      ],
    }),
  ],
  prettyHtml: true,
});
