/* eslint-disable */
/** Root.js CMS types. This file is autogenerated. */

export interface RootCMSFile {
  src: string;
  width?: number;
  height?: number;
  alt?: string;
}

export type RootCMSImage = RootCMSFile;

export type RootCMSOneOf<T = any> = T;

export type RootCMSOneOfOption<T, Base> = Base & {_type: T};

export interface RootCMSRichTextBlock {
  type: string;
  data: any;
}

export interface RootCMSRichText {
  blocks: RootCMSRichTextBlock[];
}

/** A hashed password as stored by a "password" field. */
export interface RootCMSPasswordHash {
  /** The key derivation algorithm used, e.g. "pbkdf2-sha256". */
  algorithm: string;
  /** The number of iterations used to derive the hash. */
  iterations: number;
  /** The salt used to derive the hash, base64-encoded. */
  salt: string;
  /** The derived hash, base64-encoded. */
  hash: string;
}

export interface RootCMSReference {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
}

export interface RootCMSDoc<Fields extends {}> {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
  /** System-level metadata. */
  sys: {
    createdAt: number;
    createdBy: string;
    modifiedAt: number;
    modifiedBy: string;
    firstPublishedAt?: number;
    firstPublishedBy?: string;
    publishedAt?: number;
    publishedBy?: string;
    locales?: string[];
    /**
     * Fractional-index string defining the doc's custom order within the
     * collection. See the `customSorting` collection option.
    */
    sortKey?: string;
  };
  /** User-entered field values from the CMS. */
  fields?: Fields;
}

/** Generated from `/templates/Hero/Hero.schema.ts`. */
export interface HeroFields {
  /** Title */
  title?: string;
  /** Body */
  body?: string;
  /** Image */
  image?: RootCMSImage;
}

/** Generated from `/collections/Pages.schema.ts`. */
export interface PagesFields {
  /** Meta */
  meta?: {
    /** Title. Page title. */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended: 1400x600 JPG. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Modules. Compose the page by adding one or more templates. */
    modules?: RootCMSOneOf<RootCMSOneOfOption<'Hero', HeroFields> | RootCMSOneOfOption<'Text', TextFields>>[];
  };
}

/** Generated from `/collections/Pages.schema.ts`. */
export type PagesDoc = RootCMSDoc<PagesFields>;

/** Generated from `/templates/Text/Text.schema.ts`. */
export interface TextFields {
  /** Title */
  title?: string;
  /** Body. Separate paragraphs with a blank line. */
  body?: string;
}
