import {Part, z} from 'genkit';

/** Chats can either contain a single part, or multiple parts (e.g. for attachments). */
export type ChatPrompt = Part | Part[];

/**
 * The AI chat mode.
 *
 * - chat: Used in the "Chat with Root AI" sidebar tool.
 * - edit: Used in the "Edit with AI" modal dialog for editing JSON files.
 */
export type ChatMode = 'chat' | 'edit';

export const ChatResponseSchema = z
  .object({
    message: z
      .string()
      .describe(
        'A brief message that describes what the AI did in response to the prompt, written succinctly, tersely, in a friendly but not cute tone, and be no more than a sentence or two.'
      ),
    data: z
      .any()
      .describe(
        'The JSON data payload generated by the AI conforming to the instructions from the prompt.'
      ),
  })
  .describe('The response from the AI chat request, to be used in the CMS UI.');

export type ChatResponse = z.infer<typeof ChatResponseSchema>;

/**
 * Options for constructing the prompt sent to the AI. Specify the `ChatMode`
 * and, additionally, any references to or data required to construct the
 * prompt.
 */
export interface SendPromptOptions {
  mode?: ChatMode;
  /** Data sent for edit mode requests. */
  editData?: Record<string, any>;
}
