/**
 * @fileoverview Helpers for collecting the files of a folder upload.
 *
 * Folder uploads reach the CMS two ways: through a directory picker
 * (`<input type="file" webkitdirectory>`), where each file carries a
 * `webkitRelativePath`, and through drag-and-drop, where dropped directories
 * have to be walked with the `webkitGetAsEntry()` file system API. Both
 * produce a flat list of files tagged with the folder they came from, which
 * the asset browser then mirrors into the asset library.
 */

/** A file selected for upload, along with where it lives in the upload. */
export interface UploadFileEntry {
  file: File;
  /**
   * Folder path relative to the upload destination, e.g. `'lottie/images'`.
   * Empty for files uploaded directly into the destination folder.
   */
  path: string;
}

/**
 * Max number of files collected from a single folder upload. Bounds the cost
 * of accidentally dropping a huge directory tree onto the browser.
 */
export const MAX_UPLOAD_FILES = 1000;

/** Filenames generated by OSes/tools that are never worth uploading. */
const IGNORED_FILENAMES = ['thumbs.db', 'desktop.ini'];

/** Directory names generated by OSes/tools that are skipped when walking. */
const IGNORED_DIRNAMES = ['__macosx'];

/** Returns true if a file should be skipped in a folder upload. */
export function testIgnoredUploadFile(filename: string): boolean {
  const name = (filename || '').toLowerCase();
  // Dotfiles (e.g. `.DS_Store`) are never uploaded.
  return name.startsWith('.') || IGNORED_FILENAMES.includes(name);
}

/** Returns true if a directory should be skipped in a folder upload. */
export function testIgnoredUploadDir(dirname: string): boolean {
  const name = (dirname || '').toLowerCase();
  return name.startsWith('.') || IGNORED_DIRNAMES.includes(name);
}

/**
 * Collects the files chosen from a file input. Directory pickers set a
 * `webkitRelativePath` on each file (e.g. `lottie/images/img_0.png`), which is
 * used to preserve the folder structure of the upload.
 */
export function getUploadFiles(
  files: ArrayLike<File> | null | undefined
): UploadFileEntry[] {
  const entries: UploadFileEntry[] = [];
  for (const file of Array.from(files || [])) {
    if (entries.length >= MAX_UPLOAD_FILES) {
      break;
    }
    const relativePath = (file as any).webkitRelativePath || '';
    // The last segment of the relative path is the filename itself.
    const dirs = relativePath ? relativePath.split('/').slice(0, -1) : [];
    if (testIgnoredUploadFile(file.name) || dirs.some(testIgnoredUploadDir)) {
      continue;
    }
    entries.push({file, path: dirs.filter(Boolean).join('/')});
  }
  return entries;
}

/**
 * Collects the files from a drag-and-drop event, recursively walking any
 * dropped directories. Browsers that don't support the file system entries
 * API fall back to the flat `dataTransfer.files` list.
 *
 * NOTE: `DataTransfer` is only valid for the duration of the drop event, so
 * this must be called synchronously from the event handler (the dropped items
 * are read before the first `await`).
 */
export async function getUploadFilesFromDataTransfer(
  dataTransfer: DataTransfer | null
): Promise<UploadFileEntry[]> {
  if (!dataTransfer) {
    return [];
  }
  const roots = Array.from(dataTransfer.items || [])
    .map((item) =>
      typeof item.webkitGetAsEntry === 'function'
        ? item.webkitGetAsEntry()
        : null
    )
    .filter((entry): entry is FileSystemEntry => !!entry);
  if (roots.length === 0) {
    return getUploadFiles(dataTransfer.files);
  }
  const entries: UploadFileEntry[] = [];
  for (const root of roots) {
    await collectEntry(root, '', entries);
  }
  return entries;
}

/** Recursively walks a file system entry, appending files to `entries`. */
async function collectEntry(
  entry: FileSystemEntry,
  parentPath: string,
  entries: UploadFileEntry[]
) {
  if (entries.length >= MAX_UPLOAD_FILES) {
    return;
  }
  if (entry.isFile) {
    if (testIgnoredUploadFile(entry.name)) {
      return;
    }
    entries.push({
      file: await readEntryFile(entry as FileSystemFileEntry),
      path: parentPath,
    });
    return;
  }
  if (!entry.isDirectory || testIgnoredUploadDir(entry.name)) {
    return;
  }
  const path = parentPath ? `${parentPath}/${entry.name}` : entry.name;
  const children = await readAllDirEntries(entry as FileSystemDirectoryEntry);
  for (const child of children) {
    await collectEntry(child, path, entries);
  }
}

function readEntryFile(entry: FileSystemFileEntry): Promise<File> {
  return new Promise((resolve, reject) => entry.file(resolve, reject));
}

/**
 * Reads all of a directory's entries. `readEntries()` returns results in
 * batches (chromium caps them at 100), so it's called until it comes back
 * empty.
 */
function readAllDirEntries(
  dir: FileSystemDirectoryEntry
): Promise<FileSystemEntry[]> {
  return new Promise((resolve, reject) => {
    const reader = dir.createReader();
    const results: FileSystemEntry[] = [];
    const readBatch = () => {
      reader.readEntries((batch) => {
        if (batch.length === 0) {
          resolve(results);
          return;
        }
        results.push(...batch);
        readBatch();
      }, reject);
    };
    readBatch();
  });
}
