/**
 * Word lists used by the `{adjective}` and `{noun}` tokens in `autoSlug`
 * templates. All entries must be lowercase and match the default slug regex
 * (a-z, 0-9, underscore).
 */

export const ADJECTIVES: string[] = [
  'agile', 'amber', 'amused', 'ancient', 'autumn', 'azure',
  'balmy', 'beige', 'big', 'bitter', 'black', 'blue', 'bold', 'brave',
  'breezy', 'bright', 'brisk', 'broad', 'bronze', 'brown', 'bubbly', 'busy',
  'calm', 'candid', 'careful', 'caring', 'cheerful', 'cherry', 'chilly',
  'classic', 'clean', 'clear', 'clever', 'cloudy', 'cobalt', 'cold', 'cool',
  'cosmic', 'cosy', 'cozy', 'crimson', 'crisp', 'cuddly', 'curious',
  'daring', 'dark', 'dawn', 'dazzling', 'dear', 'deep', 'delicate', 'dewy',
  'dizzy', 'dreamy', 'dry', 'dusky', 'dusty',
  'eager', 'early', 'earnest', 'easy', 'electric', 'elegant', 'emerald',
  'empty', 'epic', 'even', 'every',
  'faint', 'fair', 'falling', 'famous', 'fancy', 'fast', 'feisty', 'fierce',
  'fiery', 'fine', 'firm', 'flat', 'fluffy', 'foggy', 'fond', 'forest',
  'fragrant', 'fresh', 'friendly', 'frosty', 'funky', 'funny', 'fuzzy',
  'gentle', 'giant', 'glad', 'gleaming', 'glossy', 'gold', 'golden', 'good',
  'graceful', 'grand', 'grassy', 'gray', 'green', 'groovy',
  'happy', 'hardy', 'hazy', 'hearty', 'heavy', 'helpful', 'hidden', 'high',
  'holy', 'honest', 'hopeful', 'humble', 'humming',
  'icy', 'ideal', 'idle', 'indigo', 'inky', 'iron', 'ivory',
  'jade', 'jazzy', 'jolly', 'jovial', 'joyful', 'juicy', 'jumpy',
  'keen', 'kind',
  'lacy', 'late', 'lazy', 'lemon', 'light', 'lime', 'linen', 'little',
  'lively', 'lone', 'long', 'loud', 'lovely', 'loyal', 'lucid', 'lucky',
  'lush',
  'magenta', 'magic', 'mango', 'marble', 'maroon', 'massive', 'mauve',
  'mellow', 'merry', 'mighty', 'mild', 'milky', 'mindful', 'minty', 'misty',
  'mocha', 'modest', 'morning', 'mossy', 'muddy', 'mysterious',
  'narrow', 'navy', 'neat', 'neon', 'new', 'nimble', 'noble', 'noisy',
  'noon', 'nosy',
  'oaken', 'odd', 'old', 'olive', 'onyx', 'opal', 'open', 'orange',
  'pale', 'patient', 'peach', 'peachy', 'pearly', 'peppy', 'perky', 'pink',
  'placid', 'plain', 'playful', 'plucky', 'plum', 'plush', 'polite', 'proud',
  'pure', 'purple',
  'quaint', 'quick', 'quiet', 'quirky',
  'rapid', 'rare', 'raven', 'ready', 'red', 'restless', 'rich', 'rosy',
  'rough', 'round', 'royal', 'ruby', 'rugged', 'rustic',
  'sable', 'safe', 'sage', 'salty', 'sandy', 'sapphire', 'savvy', 'scarlet',
  'secret', 'sepia', 'serene', 'shaggy', 'sharp', 'shiny', 'short', 'shrewd',
  'shy', 'silent', 'silky', 'silly', 'silver', 'simple', 'sleek', 'sleepy',
  'slim', 'slow', 'small', 'smart', 'smoky', 'smooth', 'snappy', 'snowy',
  'soft', 'solar', 'solid', 'spicy', 'spiffy', 'spry', 'square', 'steady',
  'steel', 'sticky', 'still', 'stony', 'stormy', 'strong', 'sturdy', 'sunny',
  'super', 'swank', 'sweet', 'swift',
  'tame', 'tan', 'tart', 'teal', 'tender', 'thin', 'thirsty', 'tidy',
  'tiny', 'tireless', 'topaz', 'tough', 'tranquil', 'trim', 'true', 'twinkly',
  'umber', 'upbeat', 'urban', 'useful',
  'vast', 'velvet', 'vibrant', 'vintage', 'violet', 'vivid',
  'warm', 'watchful', 'wavy', 'wee', 'whimsical', 'whispering', 'white',
  'wild', 'windy', 'winter', 'wise', 'witty', 'woody', 'wool',
  'yellow', 'young', 'youthful',
  'zealous', 'zen', 'zesty', 'zippy',
];

export const NOUNS: string[] = [
  'acorn', 'alpaca', 'anchor', 'apple', 'apricot', 'arrow', 'autumn',
  'badger', 'bagel', 'bamboo', 'banana', 'bay', 'beach', 'bear', 'bee',
  'beetle', 'bell', 'berry', 'bird', 'biscuit', 'blossom', 'boat', 'book',
  'boot', 'bottle', 'boulder', 'branch', 'brass', 'breeze', 'bridge',
  'brook', 'broom', 'brunch', 'bubble', 'bucket', 'bud', 'buffalo', 'bug',
  'bunny', 'burrow', 'butter', 'button',
  'cabin', 'cactus', 'cake', 'camel', 'candle', 'canyon', 'cape', 'cardinal',
  'carrot', 'cat', 'cave', 'cedar', 'chair', 'cherry', 'chestnut', 'chickpea',
  'cliff', 'cloud', 'clove', 'clover', 'cocoa', 'comet', 'compass', 'cookie',
  'coral', 'cottage', 'cotton', 'cove', 'crane', 'crayon', 'creek', 'cricket',
  'crow', 'crumpet', 'crystal', 'cup', 'cupcake', 'currant', 'cypress',
  'daffodil', 'dahlia', 'daisy', 'dawn', 'deer', 'desert', 'dew', 'diamond',
  'dingo', 'dock', 'dolphin', 'donut', 'dove', 'dragon', 'drizzle', 'drum',
  'duck', 'dumpling', 'dune',
  'eagle', 'echo', 'eel', 'egg', 'elder', 'elephant', 'elk', 'ember',
  'ermine', 'estuary',
  'falcon', 'fawn', 'feather', 'fern', 'field', 'fig', 'finch', 'fir',
  'firefly', 'fish', 'flame', 'flamingo', 'flask', 'flax', 'fleece', 'flower',
  'flute', 'fog', 'forest', 'fountain', 'fox', 'frog', 'frost',
  'galaxy', 'garden', 'gecko', 'gem', 'ginger', 'glacier', 'globe', 'glow',
  'goat', 'goose', 'gorge', 'grape', 'grass', 'grove', 'gull',
  'hammock', 'hare', 'harp', 'harvest', 'hat', 'hawk', 'haystack', 'hazel',
  'heather', 'hedge', 'heron', 'hill', 'honey', 'horizon', 'horse',
  'iceberg', 'iris', 'island', 'ivy',
  'jacket', 'jade', 'jaguar', 'jam', 'jar', 'jasmine', 'jay', 'jelly',
  'juniper',
  'kayak', 'kelp', 'kettle', 'key', 'kingfisher', 'kite', 'kitten', 'koala',
  'ladybug', 'lagoon', 'lake', 'lamp', 'lantern', 'lark', 'lava', 'leaf',
  'lemon', 'lemur', 'leopard', 'lighthouse', 'lilac', 'lily', 'lime',
  'lion', 'llama', 'lobster', 'log', 'lotus', 'lynx',
  'magnet', 'mango', 'maple', 'marble', 'marlin', 'meadow', 'melody',
  'melon', 'mermaid', 'meteor', 'mint', 'mist', 'mitten', 'mole', 'monkey',
  'moon', 'moose', 'morel', 'moss', 'moth', 'mountain', 'mouse', 'muffin',
  'mushroom', 'mussel',
  'nectar', 'needle', 'nest', 'newt', 'nimbus', 'noodle', 'north', 'note',
  'oak', 'oasis', 'oats', 'ocean', 'octopus', 'olive', 'onion', 'opal',
  'orange', 'orchid', 'otter', 'owl', 'oyster',
  'paddle', 'palm', 'panda', 'pansy', 'panther', 'paper', 'parrot',
  'partridge', 'pasture', 'path', 'peach', 'peacock', 'pear', 'pebble',
  'pelican', 'penguin', 'peony', 'pepper', 'petal', 'phoenix', 'pie',
  'pigeon', 'pine', 'pineapple', 'planet', 'plover', 'plum', 'pond', 'pony',
  'poppy', 'pouch', 'prairie', 'puffin', 'pumpkin',
  'quail', 'quartz', 'queen', 'quill',
  'rabbit', 'raccoon', 'radish', 'rain', 'rainbow', 'raven', 'reef', 'reel',
  'reindeer', 'rhino', 'ribbon', 'ridge', 'river', 'road', 'robin', 'rock',
  'rose', 'rowan',
  'sage', 'salmon', 'sand', 'sapphire', 'satellite', 'scarf', 'sea',
  'seagull', 'seal', 'seed', 'shark', 'shell', 'shore', 'shrimp', 'silk',
  'silo', 'sky', 'sleet', 'snail', 'snake', 'snow', 'sock', 'spark',
  'sparrow', 'spider', 'spire', 'spoon', 'spring', 'spruce', 'squirrel',
  'star', 'starling', 'stone', 'stork', 'storm', 'stream', 'summer', 'sun',
  'sundial', 'swan', 'swift',
  'tadpole', 'tea', 'teal', 'thicket', 'thistle', 'thrush', 'thunder',
  'tide', 'tiger', 'toad', 'tooth', 'topaz', 'tortoise', 'totem', 'tower',
  'tractor', 'trail', 'tree', 'truffle', 'tulip', 'tundra', 'turtle',
  'twig', 'twilight',
  'umbrella', 'unicorn', 'urchin',
  'valley', 'vine', 'violet', 'volcano', 'vulture',
  'wagon', 'walnut', 'walrus', 'wasp', 'water', 'wave', 'whale', 'wheat',
  'whisker', 'wildcat', 'willow', 'wind', 'window', 'winter', 'wolf',
  'wombat', 'wood', 'wren',
  'yak', 'yam',
  'zebra', 'zinnia',
];
