/**
 * Word lists used by the `{adjective}` and `{noun}` tokens in `autoSlug`
 * templates. All entries must be lowercase and match the default slug regex
 * (a-z, 0-9, underscore).
 */

export const ADJECTIVES: string[] = [
  'agile', 'airy', 'alert', 'amber', 'amused', 'ancient', 'aqua', 'arctic',
  'astral', 'autumn', 'avid', 'azure',
  'balmy', 'beige', 'big', 'bitter', 'black', 'blazing', 'blissful',
  'blooming', 'blue', 'bold', 'bouncy', 'brainy', 'brave', 'breezy', 'bright',
  'brisk', 'broad', 'bronze', 'brown', 'bubbly', 'busy',
  'calm', 'candid', 'careful', 'caring', 'charming', 'cheerful', 'cherry',
  'chilly', 'chipper', 'classic', 'clean', 'clear', 'clever', 'cloudy',
  'coastal', 'cobalt', 'cold', 'cool', 'copper', 'coral', 'cosmic', 'cosy',
  'cozy', 'crafty', 'creamy', 'crimson', 'crisp', 'cuddly', 'curious',
  'dandy', 'dapper', 'daring', 'dark', 'dawn', 'dazzling', 'dear', 'deep',
  'deft', 'delicate', 'dewy', 'dizzy', 'dotted', 'dreamy', 'driven', 'dry',
  'dusky', 'dusty',
  'eager', 'early', 'earnest', 'earthy', 'eastern', 'easy', 'ebony',
  'elated', 'electric', 'elegant', 'emerald', 'empty', 'epic', 'even',
  'every',
  'faint', 'fair', 'falling', 'famous', 'fancy', 'fast', 'feisty', 'festive',
  'fierce', 'fiery', 'fine', 'firm', 'flat', 'floral', 'flowing', 'fluffy',
  'foggy', 'fond', 'forest', 'fragrant', 'fresh', 'friendly', 'frisky',
  'frosty', 'funky', 'funny', 'fuzzy',
  'gallant', 'gentle', 'giant', 'gilded', 'glad', 'gleaming', 'glossy',
  'glowing', 'gold', 'golden', 'good', 'graceful', 'grand', 'grassy', 'gray',
  'green', 'groovy', 'gusty',
  'handy', 'happy', 'hardy', 'hazy', 'hearty', 'heavy', 'helpful', 'heroic',
  'hidden', 'high', 'holy', 'honest', 'honeyed', 'hopeful', 'humble',
  'humming', 'hushed',
  'icy', 'ideal', 'idle', 'indigo', 'inky', 'iron', 'ivory',
  'jade', 'jaunty', 'jazzy', 'jolly', 'jovial', 'joyful', 'jubilant',
  'juicy', 'jumpy',
  'keen', 'kind', 'kindly',
  'lacy', 'late', 'lazy', 'leafy', 'lemon', 'light', 'limber', 'lime',
  'linen', 'little', 'lively', 'lone', 'long', 'loud', 'lovely', 'loyal',
  'lucid', 'lucky', 'luminous', 'lunar', 'lush',
  'magenta', 'magic', 'majestic', 'mango', 'marble', 'maritime', 'maroon',
  'massive', 'mauve', 'mellow', 'merry', 'mighty', 'mild', 'milky',
  'mindful', 'minty', 'misty', 'mocha', 'modest', 'morning', 'mossy',
  'muddy', 'mysterious', 'mythic',
  'narrow', 'navy', 'neat', 'neon', 'new', 'nimble', 'noble', 'noisy',
  'noon', 'northern', 'nosy', 'nutty',
  'oaken', 'oceanic', 'odd', 'old', 'olive', 'onyx', 'opal', 'open',
  'orange', 'orderly',
  'pale', 'pastel', 'patient', 'peaceful', 'peach', 'peachy', 'pearly',
  'pebbly', 'peppy', 'perky', 'pink', 'placid', 'plain', 'playful',
  'pleasant', 'plucky', 'plum', 'plush', 'polar', 'polite', 'prime',
  'pristine', 'proud', 'pure', 'purple',
  'quaint', 'quick', 'quiet', 'quirky',
  'radiant', 'rapid', 'rare', 'raven', 'ready', 'red', 'regal', 'restless',
  'rich', 'rolling', 'rosy', 'rough', 'round', 'royal', 'ruby', 'rugged',
  'rumbling', 'russet', 'rustic',
  'sable', 'safe', 'sage', 'salty', 'sandy', 'sapphire', 'savvy', 'scarlet',
  'scenic', 'secret', 'sepia', 'serene', 'shaggy', 'sharp', 'shimmering',
  'shiny', 'short', 'shrewd', 'shy', 'silent', 'silky', 'silly', 'silver',
  'simple', 'sleek', 'sleepy', 'slim', 'slow', 'small', 'smart', 'smoky',
  'smooth', 'snappy', 'snowy', 'soaring', 'soft', 'solar', 'solid',
  'southern', 'sparkly', 'speedy', 'spicy', 'spiffy', 'spotted', 'spry',
  'square', 'starry', 'steady', 'steel', 'stellar', 'sticky', 'still',
  'stony', 'stormy', 'striped', 'strong', 'sturdy', 'subtle', 'sunlit',
  'sunny', 'super', 'supreme', 'swank', 'sweet', 'swift',
  'tame', 'tan', 'tangy', 'tart', 'teal', 'tender', 'thin', 'thirsty',
  'thriving', 'tidal', 'tidy', 'tiny', 'tireless', 'toasty', 'topaz',
  'tough', 'tranquil', 'trim', 'tropical', 'true', 'twinkly',
  'umber', 'upbeat', 'urban', 'useful',
  'valiant', 'vast', 'velvet', 'verdant', 'vernal', 'vibrant', 'vintage',
  'violet', 'vivid',
  'wandering', 'warm', 'watchful', 'wavy', 'wee', 'western', 'whimsical',
  'whispering', 'white', 'wholesome', 'wild', 'winding', 'windy', 'winter',
  'wintry', 'wise', 'witty', 'wondrous', 'woody', 'wool',
  'yellow', 'young', 'youthful',
  'zany', 'zealous', 'zen', 'zesty', 'zippy',
];

export const NOUNS: string[] = [
  'acorn', 'almond', 'alpaca', 'anchor', 'antler', 'apple', 'apricot',
  'arrow', 'aspen', 'aurora', 'autumn', 'avocado',
  'badger', 'bagel', 'bamboo', 'banana', 'basil', 'bay', 'bayou', 'beach',
  'bear', 'bee', 'beetle', 'bell', 'berry', 'birch', 'bird', 'biscuit',
  'bison', 'blossom', 'bluff', 'boat', 'bobcat', 'bonfire', 'book', 'boot',
  'bottle', 'boulder', 'branch', 'brass', 'breeze', 'bridge', 'brook',
  'broom', 'brunch', 'bubble', 'bucket', 'bud', 'buffalo', 'bug', 'bunny',
  'burrow', 'butter', 'button',
  'cabin', 'cactus', 'cake', 'camel', 'canary', 'candle', 'canyon', 'cape',
  'caravan', 'cardinal', 'carrot', 'cascade', 'cashew', 'castle', 'cat',
  'cave', 'cedar', 'chair', 'cherry', 'chestnut', 'chickpea', 'chime',
  'cinnamon', 'citadel', 'cliff', 'cloud', 'clove', 'clover', 'cocoa',
  'comet', 'compass', 'condor', 'cookie', 'coral', 'cottage', 'cotton',
  'cove', 'coyote', 'crane', 'crayon', 'creek', 'cricket', 'crocus', 'crow',
  'crumpet', 'crystal', 'cup', 'cupcake', 'currant', 'cypress',
  'daffodil', 'dahlia', 'daisy', 'dawn', 'deer', 'delta', 'desert', 'dew',
  'diamond', 'dingo', 'dock', 'dogwood', 'dolphin', 'donut', 'dove',
  'dragon', 'drift', 'drizzle', 'drum', 'duck', 'dumpling', 'dune',
  'eagle', 'echo', 'eclipse', 'eel', 'egg', 'elder', 'elephant', 'elk',
  'ember', 'ermine', 'estuary', 'evergreen',
  'falcon', 'fawn', 'feather', 'fennel', 'fern', 'ferret', 'field', 'fig',
  'finch', 'fir', 'firefly', 'fish', 'fjord', 'flame', 'flamingo', 'flask',
  'flax', 'fleece', 'flicker', 'flower', 'flute', 'fog', 'forest', 'fossil',
  'fountain', 'fox', 'frog', 'frost',
  'galaxy', 'garden', 'gazelle', 'gecko', 'gem', 'geyser', 'ginger',
  'glacier', 'glade', 'glen', 'globe', 'glow', 'goat', 'goose', 'gorge',
  'gourd', 'granite', 'grape', 'grass', 'grotto', 'grove', 'gull',
  'hammock', 'harbor', 'hare', 'harp', 'harvest', 'hat', 'hawk', 'haystack',
  'hazel', 'hearth', 'heather', 'hedge', 'heron', 'hibiscus', 'hickory',
  'hill', 'hollow', 'honey', 'horizon', 'horse', 'hummingbird',
  'ibis', 'iceberg', 'icicle', 'inlet', 'iris', 'island', 'ivy',
  'jackal', 'jacket', 'jade', 'jaguar', 'jam', 'jar', 'jasmine', 'jay',
  'jelly', 'jetty', 'juniper',
  'kayak', 'kelp', 'kestrel', 'kettle', 'key', 'kingfisher', 'kite',
  'kitten', 'kiwi', 'knoll', 'koala',
  'ladybug', 'lagoon', 'lake', 'lamp', 'lantern', 'lark', 'lava',
  'lavender', 'leaf', 'ledge', 'lemon', 'lemur', 'leopard', 'lichen',
  'lighthouse', 'lilac', 'lily', 'lime', 'lion', 'llama', 'lobster', 'log',
  'loon', 'lotus', 'lynx', 'lyric',
  'magnet', 'manatee', 'mango', 'mangrove', 'maple', 'marble', 'marigold',
  'marlin', 'marsh', 'meadow', 'melody', 'melon', 'mermaid', 'mesa',
  'meteor', 'minnow', 'mint', 'mirage', 'mist', 'mitten', 'mole', 'monkey',
  'moon', 'moose', 'morel', 'mosaic', 'moss', 'moth', 'mountain', 'mouse',
  'muffin', 'mushroom', 'mussel',
  'narwhal', 'nautilus', 'nectar', 'needle', 'nest', 'nettle', 'newt',
  'nightingale', 'nimbus', 'noodle', 'north', 'note', 'nutmeg',
  'oak', 'oasis', 'oats', 'ocean', 'ocelot', 'octopus', 'olive', 'onion',
  'opal', 'orange', 'orca', 'orchid', 'oriole', 'osprey', 'otter', 'owl',
  'oyster',
  'paddle', 'palm', 'panda', 'pansy', 'panther', 'papaya', 'paper',
  'parrot', 'parsley', 'partridge', 'pasture', 'path', 'peach', 'peacock',
  'pear', 'pebble', 'pecan', 'pelican', 'penguin', 'peony', 'pepper',
  'petal', 'petunia', 'pheasant', 'phoenix', 'pie', 'pigeon', 'pine',
  'pineapple', 'pistachio', 'planet', 'plateau', 'plover', 'plum', 'pond',
  'pony', 'poppy', 'porpoise', 'pouch', 'prairie', 'pretzel', 'primrose',
  'puffin', 'pumpkin',
  'quail', 'quartz', 'queen', 'quill', 'quince', 'quokka',
  'rabbit', 'raccoon', 'radish', 'rain', 'rainbow', 'rapids', 'raspberry',
  'raven', 'redwood', 'reef', 'reel', 'reindeer', 'rhino', 'ribbon',
  'ridge', 'river', 'road', 'robin', 'rock', 'rooster', 'rose', 'rosemary',
  'rowan', 'rye',
  'saffron', 'sage', 'salmon', 'sand', 'sapphire', 'satellite', 'savanna',
  'scallop', 'scarf', 'sea', 'seagull', 'seal', 'seed', 'sequoia', 'sesame',
  'shark', 'shell', 'shore', 'shrimp', 'silk', 'silo', 'sky', 'skylark',
  'sleet', 'snail', 'snake', 'snow', 'sock', 'sorbet', 'spark', 'sparrow',
  'spider', 'spire', 'spoon', 'spring', 'sprout', 'spruce', 'squirrel',
  'star', 'starfish', 'starling', 'stone', 'stork', 'storm', 'stream',
  'summer', 'sun', 'sundial', 'sunflower', 'swan', 'swift', 'sycamore',
  'tadpole', 'tamarind', 'tangerine', 'tea', 'teal', 'tern', 'terrace',
  'thicket', 'thistle', 'thrush', 'thunder', 'tide', 'tiger', 'timber',
  'toad', 'toffee', 'tooth', 'topaz', 'tortoise', 'totem', 'toucan',
  'tower', 'tractor', 'trail', 'tree', 'trout', 'truffle', 'tugboat',
  'tulip', 'tundra', 'turnip', 'turtle', 'twig', 'twilight',
  'umbrella', 'unicorn', 'urchin',
  'valley', 'vanilla', 'vine', 'violet', 'vista', 'volcano', 'voyage',
  'vulture',
  'wagon', 'walnut', 'walrus', 'wasp', 'water', 'waterfall', 'wave',
  'whale', 'wharf', 'wheat', 'whisker', 'wildcat', 'wildflower', 'willow',
  'wind', 'window', 'winter', 'wisteria', 'wolf', 'wombat', 'wood', 'wren',
  'yak', 'yam', 'yarrow', 'yew', 'yucca',
  'zebra', 'zephyr', 'zinnia', 'zucchini',
];
