/* eslint-disable */
/** Root.js CMS types. This file is autogenerated. */

export interface RootCMSFile {
  src: string;
  width?: number;
  height?: number;
  alt?: string;
}

export type RootCMSImage = RootCMSFile;

export type RootCMSOneOf<T = any> = T;

export type RootCMSOneOfOption<T, Base> = Base & {_type: T};

export interface RootCMSRichTextBlock {
  type: string;
  data: any;
}

export interface RootCMSRichText {
  blocks: RootCMSRichTextBlock[];
}

export interface RootCMSReference {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
}

export interface RootCMSDoc<Fields extends {}> {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
  /** System-level metadata. */
  sys: {
    createdAt: number;
    createdBy: string;
    modifiedAt: number;
    modifiedBy: string;
    firstPublishedAt?: number;
    firstPublishedBy?: string;
    publishedAt?: number;
    publishedBy?: string;
    locales?: string[];
  };
  /** User-entered field values from the CMS. */
  fields?: Fields;
}

/** Generated from `/collections/BlogPosts.schema.ts`. */
export interface BlogPostsFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended size: 1200x600. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Main content body. Top content body. */
    body?: RootCMSRichText;
    /** Content blocks. Add blocks to embed various content types to the blog. */
    blocks?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>[];
  };
}

/** Generated from `/collections/BlogPosts.schema.ts`. */
export type BlogPostsDoc = RootCMSDoc<BlogPostsFields>;

/** Generated from `/components/Button/Button.schema.ts`. */
export interface ButtonFields {
  /** Button Options */
  options?: string[];
  /** Button: Label */
  label?: string;
  /** Button: ARIA Label. Optional accessibility label. */
  ariaLabel?: string;
  /** Button: URL */
  href?: string;
}

export interface ButtonsBlockFields {
  /** Block Options */
  options?: string[];
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
}

export interface CodeBlockFields {
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Language */
  language?: string;
  /** Code */
  code?: string;
}

export interface CopyBlockFields {
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Small text above the title. */
  eyebrow?: string;
  /** Title. Main headline title. */
  title?: string;
  /** Title Size */
  titleSize?: string;
  /** Body copy. Headline body copy. */
  body?: RootCMSRichText;
}

/** Generated from `/templates/Divider/Divider.schema.ts`. */
export interface DividerFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Spacer. Optional. Vertical spacing above and below the divider. */
  spacer?: {
    /** Desktop Height. Height of the spacer for the desktop layout. If blank, defaults to 80. */
    desktopHeight?: string;
    /** Tablet Height. Height of the spacer for the tablet layout. If blank, defaults to the desktop size. */
    tabletHeight?: string;
    /** Mobile Height. Height of the spacer for the mobile layout. If blank, defaults to the desktop size. */
    mobileHeight?: string;
  };
}

/** Generated from `/collections/Guide.schema.ts`. */
export interface GuideFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended size: 1200x600. */
    image?: RootCMSImage;
    /** Category */
    category?: string;
    /** Next Guide. Suggested reading next guide. */
    nextGuide?: RootCMSReference;
  };
  /** Content */
  content?: {
    /** Content title. Top content title. */
    title?: string;
    /** Content body. Top content body. */
    body?: RootCMSRichText;
    /** Sections. Each section is added to the Table of Contents. */
    sections?: {
      /** Section: ID. Section ID (for deeplinking). */
      id?: string;
      /** Section: Title. Title for the section. */
      title?: string;
      /** Section: Content body. Main content body for the section. */
      body?: RootCMSRichText;
      /** Section: Blocks. Add blocks to embed various content types to the section. */
      blocks?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>[];
    }[];
  };
}

/** Generated from `/collections/Guide.schema.ts`. */
export type GuideDoc = RootCMSDoc<GuideFields>;

export interface ImageBlockFields {
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Image */
  image?: RootCMSImage;
  /** Caption. Optional caption that displays below the image. */
  caption?: string;
  /** Advanced. These fields are optional. */
  advanced?: {
    /** Max Width. e.g. 300px */
    maxWidth?: string;
    /** Bordered? */
    bordered?: boolean;
  };
}

/** Generated from `/collections/Pages.schema.ts`. */
export interface PagesFields {
  /** Meta */
  meta?: {
    /** Title. Page title. */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended: 1400x600 JPG. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Modules. Compose the page by adding one or more modules. */
    modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'Section', SectionFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
  };
}

/** Generated from `/collections/Pages.schema.ts`. */
export type PagesDoc = RootCMSDoc<PagesFields>;

/** Generated from `/collections/Sandbox.schema.ts`. */
export interface SandboxFields {
  /** Meta */
  meta?: {
    /** Title. Page title. */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended: 1400x600 JPG. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Modules. Compose the page by adding one or more modules. */
    modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'Section', SectionFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
  };
}

/** Generated from `/collections/Sandbox.schema.ts`. */
export type SandboxDoc = RootCMSDoc<SandboxFields>;

/** Generated from `/templates/Section/Section.schema.ts`. */
export interface SectionFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Description. Required. Accessibility description for screen readers. */
  description?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Modules */
  modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
}

/** Generated from `/templates/Spacer/Spacer.schema.ts`. */
export interface SpacerFields {
  /** Desktop Height. Height of the spacer for the desktop layout. If blank, defaults to 80. */
  desktopHeight?: string;
  /** Tablet Height. Height of the spacer for the tablet layout. If blank, defaults to the desktop size. */
  tabletHeight?: string;
  /** Mobile Height. Height of the spacer for the mobile layout. If blank, defaults to the desktop size. */
  mobileHeight?: string;
}

/** Generated from `/templates/Template50x50/Template50x50.schema.ts`. */
export interface Template50x50Fields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Left Section */
  leftSection?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>;
  /** Right Section */
  rightSection?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>;
}

/** Generated from `/templates/TemplateHeadline/TemplateHeadline.schema.ts`. */
export interface TemplateHeadlineFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Small text above the title. */
  eyebrow?: string;
  /** Title. Main headline title. */
  title?: string;
  /** Body copy. Headline body copy. */
  body?: RootCMSRichText;
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
}

/** Generated from `/templates/TemplateImage/TemplateImage.schema.ts`. */
export interface TemplateImageFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Image */
  image?: RootCMSImage;
}

/** Generated from `/templates/TemplateJumplinks/TemplateJumplinks.schema.ts`. */
export interface TemplateJumplinksFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Description. Required. Accessibility description for screen readers. */
  description?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Title. Optional headline title. */
  title?: string;
  /** Links */
  links?: {
    label?: string;
    ariaLabel?: string;
    href?: string;
  }[];
}

/** Generated from `/templates/TemplatePoweredBy/TemplatePoweredBy.schema.ts`. */
export interface TemplatePoweredByFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Title */
  title?: string;
  /** Logos */
  logos?: {
    /** Logo image */
    logo?: RootCMSImage;
    /** Name */
    name?: string;
  }[];
  /** Body copy */
  body?: RootCMSRichText;
}

/** Generated from `/templates/TemplateSandbox/TemplateSandbox.schema.ts`. */
export interface TemplateSandboxFields {
  /** ImageField */
  image?: RootCMSImage;
  /** FileField */
  file?: RootCMSFile;
  /** FileField (.txt only) */
  fileTxtOnly?: RootCMSFile;
}
