/* eslint-disable */
/** Root.js CMS types. This file is autogenerated. */

export interface RootCMSFile {
  src: string;
  width?: number;
  height?: number;
  alt?: string;
}

export type RootCMSImage = RootCMSFile;

export type RootCMSOneOf<T = any> = T;

export type RootCMSOneOfOption<T, Base> = Base & {_type: T};

export interface RootCMSRichTextBlock {
  type: string;
  data: any;
}

export interface RootCMSRichText {
  blocks: RootCMSRichTextBlock[];
}

/** A hashed password as stored by a "password" field. */
export interface RootCMSPasswordHash {
  /** The key derivation algorithm used, e.g. "pbkdf2-sha256". */
  algorithm: string;
  /** The number of iterations used to derive the hash. */
  iterations: number;
  /** The salt used to derive the hash, base64-encoded. */
  salt: string;
  /** The derived hash, base64-encoded. */
  hash: string;
}

export interface RootCMSReference {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
}

export interface RootCMSDoc<Fields extends {}> {
  /** The id of the doc, e.g. "Pages/foo-bar". */
  id: string;
  /** The collection id of the doc, e.g. "Pages". */
  collection: string;
  /** The slug of the doc, e.g. "foo-bar". */
  slug: string;
  /** System-level metadata. */
  sys: {
    createdAt: number;
    createdBy: string;
    modifiedAt: number;
    modifiedBy: string;
    firstPublishedAt?: number;
    firstPublishedBy?: string;
    publishedAt?: number;
    publishedBy?: string;
    locales?: string[];
    /**
     * Fractional-index string defining the doc's custom order within the
     * collection. See the `customSorting` collection option.
    */
    sortKey?: string;
  };
  /** User-entered field values from the CMS. */
  fields?: Fields;
}

/** Generated from `/collections/BlogPosts.schema.ts`. */
export interface BlogPostsFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended size: 1200x600. */
    image?: RootCMSImage;
    /** Related Posts */
    relatedPosts?: RootCMSReference[];
  };
  /** Content */
  content?: {
    /** Main content body. Top content body. */
    body?: RootCMSRichText;
    /** Sections */
    sections?: {
      /** ID. Used for deep linking, tracking, etc. */
      id?: string;
      /** Title. Main headline title. */
      title?: string;
      /** Body copy */
      body?: RootCMSRichText;
    }[];
    /**
     * Content blocks. Deprecated. Use 'sections' instead.
     * @deprecated
    */
    blocks?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>[];
  };
}

/** Generated from `/collections/BlogPosts.schema.ts`. */
export type BlogPostsDoc = RootCMSDoc<BlogPostsFields>;

/** Generated from `/collections/BlogSandbox.schema.ts`. */
export interface BlogSandboxFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended size: 1200x600. */
    image?: RootCMSImage;
    /** Related Posts */
    relatedPosts?: RootCMSReference[];
  };
  /** Content */
  content?: {
    /** Main content body. Top content body. */
    body?: RootCMSRichText;
    /** Sections */
    sections?: {
      /** ID. Used for deep linking, tracking, etc. */
      id?: string;
      /** Title. Main headline title. */
      title?: string;
      /** Body copy */
      body?: RootCMSRichText;
    }[];
    /**
     * Content blocks. Deprecated. Use 'sections' instead.
     * @deprecated
    */
    blocks?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>[];
  };
}

/** Generated from `/collections/BlogSandbox.schema.ts`. */
export type BlogSandboxDoc = RootCMSDoc<BlogSandboxFields>;

/** Generated from `/components/Button/Button.schema.ts`. */
export interface ButtonFields {
  /** Button Options */
  options?: string[];
  /** Button: Label */
  label?: string;
  /** Button: ARIA Label. Optional accessibility label. */
  ariaLabel?: string;
  /** Button: URL */
  href?: string;
}

/** Generated from `/blocks/ButtonsBlock/ButtonsBlock.schema.ts`. */
export interface ButtonsBlockFields {
  /** Block Options */
  options?: string[];
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
}

/** Generated from `/blocks/CodeBlock/CodeBlock.schema.ts`. */
export interface CodeBlockFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Language */
  language?: string;
  /** Code */
  code?: string;
}

/** Generated from `/conditions/Conditions.schema.ts`. */
export interface ConditionsFields {
  /** Conditions */
  conditions?: RootCMSOneOf<RootCMSOneOfOption<'IsFeatureFlag', IsFeatureFlagFields> | RootCMSOneOfOption<'IsLocale', IsLocaleFields>>[];
}

/** Generated from `/blocks/CopyBlock/CopyBlock.schema.ts`. */
export interface CopyBlockFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Small text above the title. */
  eyebrow?: string;
  /** Title. Main headline title. */
  title?: string;
  /** Title Size */
  titleSize?: string;
  /** Body copy. Headline body copy. */
  body?: RootCMSRichText;
}

/** Generated from `/templates/Divider/Divider.schema.ts`. */
export interface DividerFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Spacer. Optional. Vertical spacing above and below the divider. */
  spacer?: {
    /** Desktop Height. Height of the spacer for the desktop layout. If blank, defaults to 80. */
    desktopHeight?: string;
    /** Tablet Height. Height of the spacer for the tablet layout. If blank, defaults to the desktop size. */
    tabletHeight?: string;
    /** Mobile Height. Height of the spacer for the mobile layout. If blank, defaults to the desktop size. */
    mobileHeight?: string;
  };
}

/** Generated from `/collections/Docs.schema.ts`. */
export interface DocsFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended size: 1200x600. */
    image?: RootCMSImage;
    /** Category. Sidebar group the doc is listed under. */
    category?: string;
    /** Sidebar label. Short label for the sidebar. Defaults to the content title. */
    navLabel?: string;
    /** Next Doc. Suggested doc to read next. */
    nextDoc?: RootCMSReference;
  };
  /** Content */
  content?: {
    /** Content title. Top content title. */
    title?: string;
    /** Content body. Top content body. */
    body?: RootCMSRichText;
    /** Generated reference. Adds reference docs generated from the source code after the sections. Regenerate with `node scripts/generate_reference.ts`. */
    reference?: string;
    /** Sections. Each section is added to the Table of Contents. */
    sections?: {
      /** Section: ID. Section ID (for deeplinking). */
      id?: string;
      /** Section: Title. Title for the section. */
      title?: string;
      /** Section: Content body. Main content body for the section. */
      body?: RootCMSRichText;
      /** Section: Blocks. Add blocks to embed various content types to the section. */
      blocks?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>[];
    }[];
  };
}

/** Generated from `/collections/Docs.schema.ts`. */
export type DocsDoc = RootCMSDoc<DocsFields>;

/** Generated from `/components/Emoji/Emoji.schema.ts`. */
export interface EmojiFields {
  /** Emoji */
  emojiName?: string;
}

/** Generated from `/collections/GlobalModules.schema.ts`. */
export interface GlobalModulesFields {
  /** [INTERNAL] Description. Internal description for this doc (not shown publicly). */
  internalDesc?: string;
  /** Flags. Feature flags for the site. A flag is enabled when all of its conditions are met. */
  flags?: {
    /** Name. Unique flag id, e.g. EnableFooBar. */
    name?: string;
    /** Description */
    description?: string;
    /** Conditions. The flag is enabled when all of these conditions pass. */
    conditions?: RootCMSOneOf<RootCMSOneOfOption<'IsFeatureFlag', IsFeatureFlagFields> | RootCMSOneOfOption<'IsLocale', IsLocaleFields>>[];
  }[];
}

/** Generated from `/collections/GlobalModules.schema.ts`. */
export type GlobalModulesDoc = RootCMSDoc<GlobalModulesFields>;

/** Generated from `/collections/Guides.schema.ts`. */
export interface GuidesFields {
  /** Meta */
  meta?: {
    /** Title */
    title?: string;
    /** Description. Description for SEO, social shares, and the guides index. */
    description?: string;
    /** Image. Meta image for social shares and the guides index card. */
    image?: RootCMSImage;
    /** Next guide. Suggested guide to read next. */
    nextGuide?: RootCMSReference;
  };
  /** Content */
  content?: {
    /** Eyebrow. Short label above the title, e.g. 'Publishing'. */
    eyebrow?: string;
    /** Title */
    title?: string;
    /** Intro. Opening paragraph(s): the problem and what Root.js offers. */
    intro?: RootCMSRichText;
    /** Hero image. Product screenshot shown below the intro. */
    heroImage?: RootCMSImage;
    /** Key takeaways. Short, scannable benefits shown in an 'At a glance' box. */
    takeaways?: {
      /** Text */
      text?: string;
    }[];
    /** Sections. Each section is added to the table of contents. */
    sections?: {
      /** ID. Section ID (for deeplinking). */
      id?: string;
      /** Title */
      title?: string;
      /** Body */
      body?: RootCMSRichText;
      /** Screenshot */
      image?: RootCMSImage;
      /** Screenshot caption */
      caption?: string;
    }[];
    /** Frequently asked questions */
    faq?: {
      /** Question */
      question?: string;
      /** Answer */
      answer?: string;
    }[];
  };
}

/** Generated from `/collections/Guides.schema.ts`. */
export type GuidesDoc = RootCMSDoc<GuidesFields>;

/** Generated from `/templates/If/If.schema.ts`. */
export interface IfFields {
  /** [INTERNAL] Description. e.g. 'Show hero only when the EnableNewHero flag is on'. */
  internalDesc?: string;
  /** Conditions. Nested modules render only when all of these conditions pass. */
  conditions?: RootCMSOneOf<RootCMSOneOfOption<'IsFeatureFlag', IsFeatureFlagFields> | RootCMSOneOfOption<'IsLocale', IsLocaleFields>>[];
  /** Modules (if TRUE). Rendered when all conditions are satisfied. */
  modulesIfTrue?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
  /** Modules (if FALSE). Rendered when the conditions are NOT satisfied. */
  modulesIfFalse?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
}

/** Generated from `/blocks/ImageBlock/ImageBlock.schema.ts`. */
export interface ImageBlockFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Image */
  image?: RootCMSImage;
  /** Caption. Optional caption that displays below the image. */
  caption?: string;
  /** Advanced. These fields are optional. */
  advanced?: {
    /** Max Width. e.g. 300px */
    maxWidth?: string;
    /** Bordered? */
    bordered?: boolean;
  };
}

/** Generated from `/conditions/IsFeatureFlag/IsFeatureFlag.schema.ts`. */
export interface IsFeatureFlagFields {
  /** [INTERNAL] Description */
  internalDesc?: string;
  /** Flag. Pick a flag defined in GlobalModules/flags, or type a new one. */
  flag?: string;
}

/** Generated from `/conditions/IsLocale/IsLocale.schema.ts`. */
export interface IsLocaleFields {
  /** [INTERNAL] Description */
  internalDesc?: string;
  /** Locale(s). Locales to match, e.g. 'en', 'de'. Leave empty to match all. */
  locales?: string[];
}

/** Generated from `/collections/Pages.schema.ts`. */
export interface PagesFields {
  /** Meta */
  meta?: {
    /** Title. Page title. */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended: 1400x600 JPG. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Modules. Compose the page by adding one or more modules. */
    modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'If', IfFields> | RootCMSOneOfOption<'Section', SectionFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
  };
}

/** Generated from `/collections/Pages.schema.ts`. */
export type PagesDoc = RootCMSDoc<PagesFields>;

/** Generated from `/collections/Sandbox.schema.ts`. */
export interface SandboxFields {
  /** Meta */
  meta?: {
    /** Title. Page title. */
    title?: string;
    /** Description. Description for SEO and social shares. */
    description?: string;
    /** Image. Meta image for social shares. Recommended: 1400x600 JPG. */
    image?: RootCMSImage;
  };
  /** Content */
  content?: {
    /** Modules. Compose the page by adding one or more modules. */
    modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'If', IfFields> | RootCMSOneOfOption<'Section', SectionFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
  };
}

/** Generated from `/collections/Sandbox.schema.ts`. */
export type SandboxDoc = RootCMSDoc<SandboxFields>;

/** Generated from `/templates/Section/Section.schema.ts`. */
export interface SectionFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Description. Required. Accessibility description for screen readers. */
  description?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Modules */
  modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'If', IfFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
}

/** Generated from `/templates/Spacer/Spacer.schema.ts`. */
export interface SpacerFields {
  /** Desktop Height. Height of the spacer for the desktop layout. If blank, defaults to 80. */
  desktopHeight?: string;
  /** Tablet Height. Height of the spacer for the tablet layout. If blank, defaults to the desktop size. */
  tabletHeight?: string;
  /** Mobile Height. Height of the spacer for the mobile layout. If blank, defaults to the desktop size. */
  mobileHeight?: string;
}

/** Generated from `/templates/Template50x50/Template50x50.schema.ts`. */
export interface Template50x50Fields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Left Section */
  leftSection?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>;
  /** Right Section */
  rightSection?: RootCMSOneOf<RootCMSOneOfOption<'ButtonsBlock', ButtonsBlockFields> | RootCMSOneOfOption<'CodeBlock', CodeBlockFields> | RootCMSOneOfOption<'CopyBlock', CopyBlockFields> | RootCMSOneOfOption<'ImageBlock', ImageBlockFields>>;
}

/** Generated from `/templates/TemplateBlogPosts/TemplateBlogPosts.schema.ts`. */
export interface TemplateBlogPostsFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Eyebrow */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: RootCMSRichText;
}

/** Generated from `/templates/TemplateCodeShowcase/TemplateCodeShowcase.schema.ts`. */
export interface TemplateCodeShowcaseFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: string;
  /** Files. Shown side by side on desktop (up to 3). */
  files?: {
    /** Filename. e.g. 'collections/Pages.schema.ts'. */
    filename?: string;
    /** Caption. Optional. Short note shown above the code. */
    caption?: string;
    /** Language */
    language?: string;
    /** Code */
    code?: string;
  }[];
}

/** Generated from `/templates/TemplateFeatureGrid/TemplateFeatureGrid.schema.ts`. */
export interface TemplateFeatureGridFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. Defaults to 3 columns. */
  options?: string[];
  /** Eyebrow */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: string;
  /** Items */
  items?: {
    /** Icon. Optional. Icon shown above the title. */
    icon?: string;
    /** Title */
    title?: string;
    /** Body copy. One or two sentences. */
    body?: string;
    /** URL. Optional. Makes the whole item a link, e.g. to a guide. */
    href?: string;
  }[];
}

/** Generated from `/templates/TemplateFeatureSpotlight/TemplateFeatureSpotlight.schema.ts`. */
export interface TemplateFeatureSpotlightFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Usually the feature name, e.g. 'Root AI'. */
  eyebrow?: string;
  /** Title. The feature tagline. */
  title?: string;
  /** Body copy */
  body?: RootCMSRichText;
  /** Highlights. Short supporting points, shown as a checklist. */
  highlights?: {
    /** Text */
    text?: string;
  }[];
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
  /** Image. Product screenshot. Recommended: 1920x1200 PNG. */
  image?: RootCMSImage;
}

/** Generated from `/templates/TemplateGuides/TemplateGuides.schema.ts`. */
export interface TemplateGuidesFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Eyebrow */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: RootCMSRichText;
  /** Docs link. Line below the header that points developers to the docs. */
  docsLink?: RootCMSRichText;
}

/** Generated from `/templates/TemplateHeadline/TemplateHeadline.schema.ts`. */
export interface TemplateHeadlineFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Small text above the title. */
  eyebrow?: string;
  /** Title. Main headline title. */
  title?: string;
  /** Body copy. Headline body copy. */
  body?: RootCMSRichText;
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
}

/** Generated from `/templates/TemplateHero/TemplateHero.schema.ts`. */
export interface TemplateHeroFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow. Small text above the title. */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: RootCMSRichText;
  /** Buttons */
  buttons?: {
    /** Button Options */
    options?: string[];
    /** Button: Label */
    label?: string;
    /** Button: ARIA Label. Optional accessibility label. */
    ariaLabel?: string;
    /** Button: URL */
    href?: string;
  }[];
  /** Command. Optional. Shell command shown below the buttons, e.g. `npm create @blinkk/root`. */
  command?: string;
  /** Image. Optional. Product screenshot shown below the copy. Recommended: 2880x1800 PNG. */
  image?: RootCMSImage;
}

/** Generated from `/templates/TemplateImage/TemplateImage.schema.ts`. */
export interface TemplateImageFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Image */
  image?: RootCMSImage;
}

/** Generated from `/templates/TemplateJumplinks/TemplateJumplinks.schema.ts`. */
export interface TemplateJumplinksFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Description. Required. Accessibility description for screen readers. */
  description?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Title. Optional headline title. */
  title?: string;
  /** Links */
  links?: {
    label?: string;
    ariaLabel?: string;
    href?: string;
  }[];
}

/** Generated from `/templates/TemplatePillars/TemplatePillars.schema.ts`. */
export interface TemplatePillarsFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Eyebrow */
  eyebrow?: string;
  /** Title */
  title?: string;
  /** Body copy */
  body?: string;
  /** Pillars */
  pillars?: {
    /** Icon. Optional. Icon shown above the title. */
    icon?: string;
    /** Eyebrow. e.g. 'Build'. */
    eyebrow?: string;
    /** Title */
    title?: string;
    /** Body copy */
    body?: string;
    /** Bullets */
    bullets?: {
      /** Text */
      text?: string;
    }[];
    /** Link */
    link?: {
      /** Label */
      label?: string;
      /** URL */
      href?: string;
    };
  }[];
}

/** Generated from `/templates/TemplatePoweredBy/TemplatePoweredBy.schema.ts`. */
export interface TemplatePoweredByFields {
  /** ID. Used for deep linking, tracking, etc. */
  id?: string;
  /** Module Options. Layout and display options. */
  options?: string[];
  /** Title */
  title?: string;
  /** Logos */
  logos?: {
    /** Logo image */
    logo?: RootCMSImage;
    /** Name */
    name?: string;
  }[];
  /** Body copy */
  body?: RootCMSRichText;
}

/** Generated from `/templates/TemplateSandbox/TemplateSandbox.schema.ts`. */
export interface TemplateSandboxFields {
  /** ImageField */
  image?: RootCMSImage;
  /** FileField */
  file?: RootCMSFile;
  /** FileField (.txt only) */
  fileTxtOnly?: RootCMSFile;
  /** ReferencesField */
  references?: RootCMSReference[];
  /** DateTimeField */
  datetime?: number;
  /** DateTimeField */
  datetimeWithTimezone?: number;
  /** DateField */
  date?: string;
  /** PasswordField. Stored as a salted hash; verify with cmsClient.verifyPassword(). */
  password?: RootCMSPasswordHash;
  /** StringField (Textarea) */
  string?: string;
  /** StringField (JSON) */
  jsonString?: string;
  /** RichTextField */
  richtext?: RootCMSRichText;
  /** Modules */
  modules?: RootCMSOneOf<RootCMSOneOfOption<'Divider', DividerFields> | RootCMSOneOfOption<'If', IfFields> | RootCMSOneOfOption<'Section', SectionFields> | RootCMSOneOfOption<'Spacer', SpacerFields> | RootCMSOneOfOption<'Template50x50', Template50x50Fields> | RootCMSOneOfOption<'TemplateBlogPosts', TemplateBlogPostsFields> | RootCMSOneOfOption<'TemplateCodeShowcase', TemplateCodeShowcaseFields> | RootCMSOneOfOption<'TemplateFeatureGrid', TemplateFeatureGridFields> | RootCMSOneOfOption<'TemplateFeatureSpotlight', TemplateFeatureSpotlightFields> | RootCMSOneOfOption<'TemplateGuides', TemplateGuidesFields> | RootCMSOneOfOption<'TemplateHeadline', TemplateHeadlineFields> | RootCMSOneOfOption<'TemplateHero', TemplateHeroFields> | RootCMSOneOfOption<'TemplateImage', TemplateImageFields> | RootCMSOneOfOption<'TemplateJumplinks', TemplateJumplinksFields> | RootCMSOneOfOption<'TemplatePillars', TemplatePillarsFields> | RootCMSOneOfOption<'TemplatePoweredBy', TemplatePoweredByFields> | RootCMSOneOfOption<'TemplateSandbox', TemplateSandboxFields>>[];
}
