name: Release

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

env:
  FORCE_COLOR: true

# Allow OIDC tokens to be written for publishing to npm.
# https://docs.npmjs.com/trusted-publishers#step-2-configure-your-cicd-workflow
permissions:
  id-token: write
  contents: write

jobs:
  changelog:
    name: Changelog PR or Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # A newer version of npm is required for publishing with OIDC.
      - name: Update npm
        run: |
          npm install -g npm@latest

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: '8.9.0'
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install playwright deps
        working-directory: ./packages/root-cms
        run: pnpm exec playwright install

      - name: Unit tests
        run: pnpm test

      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm run version
          publish: pnpm run release:ci
          commit: 'ci: release'
          title: 'ci: release'
        env:
          # Needs access to push to main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # Use OIDC for npm authentication instead of NPM_TOKEN
          NPM_TOKEN: ''
